# main variables
CLIENT_HOST = 'CLIENT_HOST'
CLIENT_API_URL = 'CLIENT_API_URL'
LOGGER_CONFIGURATION_FILE = 'LOGGER_CONFIGURATION_FILE'
BASIC_AUTH_PROMETHEUS_USER = 'BASIC_AUTH_PROMETHEUS_USER'
BASIC_AUTH_PROMETHEUS_PASSWORD = 'BASIC_AUTH_PROMETHEUS_PASSWORD'
BASIC_AUTH_CLIENT_USER = 'BASIC_AUTH_CLIENT_USER'
BASIC_AUTH_CLIENT_PASSWORD = 'BASIC_AUTH_CLIENT_PASSWORD'
BASIC_AUTH_CORE_USER = 'BASIC_AUTH_CORE_USER'
BASIC_AUTH_CORE_PASSWORD = 'BASIC_AUTH_CORE_PASSWORD'


